spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linkee
    username: linkee
    password: linkee

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:charlymarket001@gmail.com}
    password: ${MAIL_PASSWORD:uxjg kacj xyns wvno}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.from: ${MAIL_FROM:charlymarket001@gmail.com}
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update           # create, create-drop, update, validate, none 중 선택
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # 성능상 권장 옵션


jwt:
  secret: rA/4r9fDxHVDBouXITwYw4nxNgmgshmA72NnxVpassNqZ038QCTpWznTn1UbekAwApd6oOA3/wixuu+4i0g2ww==
  access-expiration: 600000      # 10분
  refresh-expiration: 3600000    # 1시간

auth:
  code:
    expiration-millis: 300000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.linkee.linkeeapi.**

