spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linkee
    username: linkee
    password: linkee

  jpa:
    hibernate:
      ddl-auto: update           # create, create-drop, update, validate, none 중 선택
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # 성능상 권장 옵션
