# ??? ?? ???? ???? 5~6?? ?? ????? ??
server:
  port: 0

# Eureka
eureka:
  # Eureka Server UI ?? ???? ?? ???? ?? id ??
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}

  client:
    fetch-registry: true
    # ??? ??? ?? ???? ??
    register-with-eureka: true
    service-url:
      # ??? ?? ?? url ??
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: linkee-chat-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linkee
    username: linkee
    password: linkee

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: mongodb+srv://kimsangjaemongodb:kimsangjaemongodb@cluster0.o9c574k.mongodb.net/linkee?retryWrites=true&w=majority&appName=Cluster0

  jpa:
    hibernate:
      ddl-auto: update           # create, create-drop, update, validate, none ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # ??? ?? ??

  #?? "???"???
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 7GC7QekquJkdHHW5g9ZS
            client-secret: PKtfCnWeiA
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  secret: rA/4r9fDxHVDBouXITwYw4nxNgmgshmA72NnxVpassNqZ038QCTpWznTn1UbekAwApd6oOA3/wixuu+4i0g2ww==
  access-expiration: 600000      # 10?
  refresh-expiration: 3600000    # 1??

auth:
  code:
    expiration-millis: 300000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.linkee.linkeeapi.**




