# 스케일 아웃 상황에서 랜덤하게 5~6만번 대의 포트번호를 부여
server:
  port: 0
# Eureka
eureka:
  # Eureka Server UI 에서 구별되기 위해 포트번호 랜덤 id 설정
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}

  client:
    fetch-registry: true
    # 유레카 서버에 해당 인스턴스 등록
    register-with-eureka: true
    service-url:
      # 유레카 서버 기본 url 설정
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: linkee-user-service



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linkee
    username: linkee
    password: linkee

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:charlymarket001@gmail.com}
    password: ${MAIL_PASSWORD:uxjg kacj xyns wvno}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.from: ${MAIL_FROM:charlymarket001@gmail.com}

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: mongodb+srv://kimsangjaemongodb:kimsangjaemongodb@cluster0.o9c574k.mongodb.net/linkee?retryWrites=true&w=majority&appName=Cluster0

  jpa:
    hibernate:
      ddl-auto: update           # create, create-drop, update, validate, none 중 선택
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # 성능상 권장 옵션

#여기 "유한세"추가함
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 7GC7QekquJkdHHW5g9ZS
            client-secret: PKtfCnWeiA
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  secret: rA/4r9fDxHVDBouXITwYw4nxNgmgshmA72NnxVpassNqZ038QCTpWznTn1UbekAwApd6oOA3/wixuu+4i0g2ww==
  access-expiration: 600000      # 10분
  refresh-expiration: 3600000    # 1시간

auth:
  code:
    expiration-millis: 300000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.linkee.linkeeapi.**




